Content:
    - ${ROOT_DIR}/content
    - moose_site_assets:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - js/*
            - css/*
            - contrib/**
            - media/framework/github-logo.png
            - media/framework/github-mark.png
            - media/framework/github-mark-light.png

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    extra-css:
        - css/shannonlab.css

Extensions:
    MooseDocs.extensions.navigation:
        name: 4-STAR Group
        repo: https://github.com/shannon-lab/
    MooseDocs.extensions.appsyntax:
        active: False
